import { Page, Response } from "@playwright/test";

/**
 * Resolve the test-control token from the environment exactly once.
 *
 * The token is generated by the caller (e.g.
 * ``BIDSCOPE_TEST_CONTROL_TOKEN="e2e-$(date +%s)" npm run test:e2e``) and
 * forwarded to the API server via the webServer env in playwright.config.ts.
 * It must be set before any helper that calls a ``/api/test-controls/*`` route
 * is used; a missing token throws with a clear message instead of an opaque
 * 401 from the server.
 */
function requireTestControlToken(): string {
  const token = process.env.BIDSCOPE_TEST_CONTROL_TOKEN;
  if (!token) {
    throw new Error(
      "BIDSCOPE_TEST_CONTROL_TOKEN is not set; the test-control endpoints require it. " +
        'Export it before running E2E, e.g. ' +
        'BIDSCOPE_TEST_CONTROL_TOKEN="e2e-$(date +%s)" npm run test:e2e',
    );
  }
  return token;
}

/**
 * Call the test-only import-batch-2 endpoint to import the demo batch-2 bundle.
 * Only available when the server runs with BIDSCOPE_APP_MODE=test.
 */
export async function importBatch2(page: Page): Promise<Response> {
  return page.request.post("/api/test-controls/import-batch-2", {
    headers: { "X-Test-Control-Token": requireTestControlToken() },
  });
}

/**
 * Configure the test-only control to fail the next node execution.
 * The failure is one-shot: it applies to the very next run and is then cleared.
 */
export async function configureFailNextNode(
  page: Page,
  node: string,
): Promise<Response> {
  return page.request.post("/api/test-controls/fail-next-node", {
    headers: { "X-Test-Control-Token": requireTestControlToken() },
    data: { node },
  });
}

/**
 * Run one subscription scheduler tick via the test-only endpoint.
 *
 * The endpoint drives ``run_scheduler_tick`` with a far-future ``now`` so every
 * active subscription is considered due, letting E2E exercise the full
 * subscription/inbox pipeline (advisory lock, graph execution, notice diff,
 * inbox events) without waiting for the next cron occurrence. The tick runs
 * in-process inside the API server, so no separate scheduler process or CLI
 * subprocess is required.
 */
export async function runSchedulerTick(page: Page): Promise<Response> {
  return page.request.post("/api/test-controls/run-scheduler-tick", {
    headers: { "X-Test-Control-Token": requireTestControlToken() },
  });
}

