"""evidence闭环 and non-null idempotency keys

Revision ID: 2120994560c7
Revises: 309c4994f75f
Create Date: 2026-07-19 11:33:49.077161

"""
from typing import Union, Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '2120994560c7'
down_revision: Union[str, None] = '309c4994f75f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('eval_cases',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('dataset_version', sa.Text(), nullable=False),
    sa.Column('case_key', sa.Text(), nullable=False),
    sa.Column('inputs', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('expected_outputs', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_eval_cases')),
    sa.UniqueConstraint('case_key', name=op.f('uq_eval_cases_case_key'))
    )
    op.create_table('report_citations',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('report_item_id', sa.Uuid(), nullable=False),
    sa.Column('evidence_id', sa.Uuid(), nullable=False),
    sa.Column('label', sa.Text(), nullable=True),
    sa.Column('span_start', sa.Integer(), nullable=True),
    sa.Column('span_end', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['evidence_id'], ['notice_evidence.id'], name=op.f('fk_report_citations_evidence_id_notice_evidence')),
    sa.ForeignKeyConstraint(['report_item_id'], ['report_items.id'], name=op.f('fk_report_citations_report_item_id_report_items')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_report_citations'))
    )
    op.create_index(op.f('ix_report_citations_evidence_id'), 'report_citations', ['evidence_id'], unique=False)
    op.create_index(op.f('ix_report_citations_report_item_id'), 'report_citations', ['report_item_id'], unique=False)
    op.create_table('report_claims',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('report_item_id', sa.Uuid(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('claim_type', sa.Text(), server_default=sa.text("'factual'"), nullable=False),
    sa.Column('evidence_span_id', sa.Uuid(), nullable=True),
    sa.Column('confidence', sa.Float(), server_default=sa.text('0.0'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['evidence_span_id'], ['notice_evidence.id'], name=op.f('fk_report_claims_evidence_span_id_notice_evidence')),
    sa.ForeignKeyConstraint(['report_item_id'], ['report_items.id'], name=op.f('fk_report_claims_report_item_id_report_items')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_report_claims'))
    )
    op.create_index(op.f('ix_report_claims_evidence_span_id'), 'report_claims', ['evidence_span_id'], unique=False)
    op.create_index(op.f('ix_report_claims_report_item_id'), 'report_claims', ['report_item_id'], unique=False)
    op.alter_column('query_runs', 'run_key',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('reports', 'export_key',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('snapshot_imports', 'idempotency_key',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('subscriptions', 'trigger_key',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('subscriptions', 'trigger_key',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('snapshot_imports', 'idempotency_key',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('reports', 'export_key',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('query_runs', 'run_key',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_index(op.f('ix_report_claims_report_item_id'), table_name='report_claims')
    op.drop_index(op.f('ix_report_claims_evidence_span_id'), table_name='report_claims')
    op.drop_table('report_claims')
    op.drop_index(op.f('ix_report_citations_report_item_id'), table_name='report_citations')
    op.drop_index(op.f('ix_report_citations_evidence_id'), table_name='report_citations')
    op.drop_table('report_citations')
    op.drop_table('eval_cases')
    # ### end Alembic commands ###
