"""initial

Revision ID: 309c4994f75f
Revises: 
Create Date: 2026-07-19 09:27:30.033203

"""
from typing import Union, Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector.sqlalchemy.vector  # noqa: F401  # noqa: F401

revision: str = '309c4994f75f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    op.create_table('canonical_notices',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_canonical_notices'))
    )
    op.create_table('eval_runs',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('dataset_version', sa.Text(), nullable=False),
    sa.Column('model', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('environment', sa.Text(), nullable=True),
    sa.Column('pricing_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_eval_runs'))
    )
    op.create_table('query_runs',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('run_key', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('user_request', sa.Text(), nullable=False),
    sa.Column('search_intent', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('error', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('token_usage', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('checkpoint_thread_id', sa.Text(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_query_runs')),
    sa.UniqueConstraint('run_key', name=op.f('uq_query_runs_run_key'))
    )
    op.create_table('snapshot_bundles',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('bundle_id', sa.Text(), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('capture_kind', sa.Text(), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('source_urls', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('retrieval_outcome', sa.Text(), nullable=False),
    sa.Column('parser_version', sa.Text(), nullable=False),
    sa.Column('manifest', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_snapshot_bundles')),
    sa.UniqueConstraint('bundle_id', name=op.f('uq_snapshot_bundles_bundle_id'))
    )
    op.create_table('subscriptions',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('cron_expression', sa.Text(), nullable=False),
    sa.Column('timezone', sa.Text(), server_default=sa.text("'Asia/Shanghai'"), nullable=False),
    sa.Column('normalized_intent', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('last_successful_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('trigger_key', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subscriptions')),
    sa.UniqueConstraint('trigger_key', name=op.f('uq_subscriptions_trigger_key'))
    )
    op.create_table('reports',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('run_id', sa.Uuid(), nullable=True),
    sa.Column('export_key', sa.Text(), nullable=True),
    sa.Column('conditions', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('freshness_window', sa.Text(), nullable=True),
    sa.Column('completeness_warning', sa.Text(), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('docx_object_key', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['query_runs.id'], name=op.f('fk_reports_run_id_query_runs')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reports')),
    sa.UniqueConstraint('export_key', name=op.f('uq_reports_export_key'))
    )
    op.create_index(op.f('ix_reports_run_id'), 'reports', ['run_id'], unique=False)
    op.create_table('run_events',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('query_run_id', sa.Uuid(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('node', sa.Text(), nullable=False),
    sa.Column('event', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['query_run_id'], ['query_runs.id'], name=op.f('fk_run_events_query_run_id_query_runs')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_run_events')),
    sa.UniqueConstraint('query_run_id', 'seq', name='uq_run_events_query_run_id_seq')
    )
    op.create_index(op.f('ix_run_events_query_run_id'), 'run_events', ['query_run_id'], unique=False)
    op.create_table('snapshot_imports',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('snapshot_bundle_id', sa.Uuid(), nullable=False),
    sa.Column('idempotency_key', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('warnings', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['snapshot_bundle_id'], ['snapshot_bundles.id'], name=op.f('fk_snapshot_imports_snapshot_bundle_id_snapshot_bundles')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_snapshot_imports')),
    sa.UniqueConstraint('idempotency_key', name=op.f('uq_snapshot_imports_idempotency_key'))
    )
    op.create_index(op.f('ix_snapshot_imports_snapshot_bundle_id'), 'snapshot_imports', ['snapshot_bundle_id'], unique=False)
    op.create_table('source_notices',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('canonical_notice_id', sa.Uuid(), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('external_id', sa.Text(), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('latest_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('content_hash', sa.Text(), nullable=False),
    sa.Column('project_number', sa.Text(), nullable=True),
    sa.Column('purchaser', sa.Text(), nullable=True),
    sa.Column('region', sa.Text(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['canonical_notice_id'], ['canonical_notices.id'], name=op.f('fk_source_notices_canonical_notice_id_canonical_notices')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_source_notices')),
    sa.UniqueConstraint('source', 'external_id', name='uq_source_notices_source_external_id')
    )
    op.create_index(op.f('ix_source_notices_canonical_notice_id'), 'source_notices', ['canonical_notice_id'], unique=False)
    op.create_table('inbox_events',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('subscription_id', sa.Uuid(), nullable=True),
    sa.Column('event_type', sa.Text(), nullable=False),
    sa.Column('notice_id', sa.Uuid(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('read', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['notice_id'], ['source_notices.id'], name=op.f('fk_inbox_events_notice_id_source_notices')),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], name=op.f('fk_inbox_events_subscription_id_subscriptions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inbox_events'))
    )
    op.create_index(op.f('ix_inbox_events_notice_id'), 'inbox_events', ['notice_id'], unique=False)
    op.create_index(op.f('ix_inbox_events_subscription_id'), 'inbox_events', ['subscription_id'], unique=False)
    op.create_table('notice_versions',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('source_notice_id', sa.Uuid(), nullable=False),
    sa.Column('payload_object_key', sa.Text(), nullable=False),
    sa.Column('capture_kind', sa.Text(), nullable=False),
    sa.Column('parser_version', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('purchaser', sa.Text(), nullable=True),
    sa.Column('region', sa.Text(), nullable=True),
    sa.Column('publish_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('budget_minor_units', sa.BigInteger(), nullable=True),
    sa.Column('budget_currency', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('raw_fields', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_notice_id'], ['source_notices.id'], name=op.f('fk_notice_versions_source_notice_id_source_notices')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notice_versions')),
    sa.UniqueConstraint('source_notice_id', 'content_hash', name='uq_notice_versions_source_notice_id_content_hash')
    )
    op.create_index(op.f('ix_notice_versions_source_notice_id'), 'notice_versions', ['source_notice_id'], unique=False)
    op.create_table('subscription_seen_items',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('subscription_id', sa.Uuid(), nullable=False),
    sa.Column('notice_id', sa.Uuid(), nullable=False),
    sa.Column('version_content_hash', sa.Text(), nullable=False),
    sa.Column('seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['notice_id'], ['source_notices.id'], name=op.f('fk_subscription_seen_items_notice_id_source_notices')),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], name=op.f('fk_subscription_seen_items_subscription_id_subscriptions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subscription_seen_items')),
    sa.UniqueConstraint('subscription_id', 'notice_id', name='uq_subscription_seen_items_subscription_id_notice_id')
    )
    op.create_index(op.f('ix_subscription_seen_items_notice_id'), 'subscription_seen_items', ['notice_id'], unique=False)
    op.create_index(op.f('ix_subscription_seen_items_subscription_id'), 'subscription_seen_items', ['subscription_id'], unique=False)
    op.create_table('notice_evidence',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('notice_version_id', sa.Uuid(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('start', sa.Integer(), nullable=False),
    sa.Column('end', sa.Integer(), nullable=False),
    sa.Column('span_hash', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['notice_version_id'], ['notice_versions.id'], name=op.f('fk_notice_evidence_notice_version_id_notice_versions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notice_evidence'))
    )
    op.create_index(op.f('ix_notice_evidence_notice_version_id'), 'notice_evidence', ['notice_version_id'], unique=False)
    op.create_table('report_items',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('report_id', sa.Uuid(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('notice_version_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('known_fields', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('unknown_fields', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('relevance_reason', sa.Text(), nullable=True),
    sa.Column('risk_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['notice_version_id'], ['notice_versions.id'], name=op.f('fk_report_items_notice_version_id_notice_versions')),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], name=op.f('fk_report_items_report_id_reports')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_report_items'))
    )
    op.create_index(op.f('ix_report_items_notice_version_id'), 'report_items', ['notice_version_id'], unique=False)
    op.create_index(op.f('ix_report_items_report_id'), 'report_items', ['report_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_report_items_report_id'), table_name='report_items')
    op.drop_index(op.f('ix_report_items_notice_version_id'), table_name='report_items')
    op.drop_table('report_items')
    op.drop_index(op.f('ix_notice_evidence_notice_version_id'), table_name='notice_evidence')
    op.drop_table('notice_evidence')
    op.drop_index(op.f('ix_subscription_seen_items_subscription_id'), table_name='subscription_seen_items')
    op.drop_index(op.f('ix_subscription_seen_items_notice_id'), table_name='subscription_seen_items')
    op.drop_table('subscription_seen_items')
    op.drop_index(op.f('ix_notice_versions_source_notice_id'), table_name='notice_versions')
    op.drop_table('notice_versions')
    op.drop_index(op.f('ix_inbox_events_subscription_id'), table_name='inbox_events')
    op.drop_index(op.f('ix_inbox_events_notice_id'), table_name='inbox_events')
    op.drop_table('inbox_events')
    op.drop_index(op.f('ix_source_notices_canonical_notice_id'), table_name='source_notices')
    op.drop_table('source_notices')
    op.drop_index(op.f('ix_snapshot_imports_snapshot_bundle_id'), table_name='snapshot_imports')
    op.drop_table('snapshot_imports')
    op.drop_index(op.f('ix_run_events_query_run_id'), table_name='run_events')
    op.drop_table('run_events')
    op.drop_index(op.f('ix_reports_run_id'), table_name='reports')
    op.drop_table('reports')
    op.drop_table('subscriptions')
    op.drop_table('snapshot_bundles')
    op.drop_table('query_runs')
    op.drop_table('eval_runs')
    op.drop_table('canonical_notices')
    # ### end Alembic commands ###
