"""run_events timestamp

Revision ID: a1b2c3d4e5f6
Revises: c7a5e1d3a2f4
Create Date: 2026-07-20 08:30:00.000000

"""
from typing import Union, Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'a1b2c3d4e5f6'
down_revision: Union[str, None] = 'c7a5e1d3a2f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'run_events',
        sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False, server_default=sa.text('now()')),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('run_events', 'timestamp')
    # ### end Alembic commands ###
