"""claim to evidence relationships

Revision ID: b44cc923895e
Revises: 2120994560c7
Create Date: 2026-07-19 12:26:32.102534

"""
from typing import Union, Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'b44cc923895e'
down_revision: Union[str, None] = '2120994560c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('report_claim_citations',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('report_claim_id', sa.Uuid(), nullable=False),
    sa.Column('evidence_id', sa.Uuid(), nullable=False),
    sa.Column('label', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['evidence_id'], ['notice_evidence.id'], name=op.f('fk_report_claim_citations_evidence_id_notice_evidence')),
    sa.ForeignKeyConstraint(['report_claim_id'], ['report_claims.id'], name=op.f('fk_report_claim_citations_report_claim_id_report_claims')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_report_claim_citations')),
    sa.UniqueConstraint('report_claim_id', 'evidence_id', name='uq_report_claim_citations_report_claim_id_evidence_id')
    )
    op.create_index(op.f('ix_report_claim_citations_evidence_id'), 'report_claim_citations', ['evidence_id'], unique=False)
    op.create_index(op.f('ix_report_claim_citations_report_claim_id'), 'report_claim_citations', ['report_claim_id'], unique=False)
    op.drop_index(op.f('ix_report_claims_evidence_span_id'), table_name='report_claims')
    op.drop_constraint(op.f('fk_report_claims_evidence_span_id_notice_evidence'), 'report_claims', type_='foreignkey')
    op.drop_column('report_claims', 'confidence')
    op.drop_column('report_claims', 'claim_type')
    op.drop_column('report_claims', 'evidence_span_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('report_claims', sa.Column('evidence_span_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('report_claims', sa.Column('claim_type', sa.TEXT(), server_default=sa.text("'factual'::text"), autoincrement=False, nullable=False))
    op.add_column('report_claims', sa.Column('confidence', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('0.0'), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('fk_report_claims_evidence_span_id_notice_evidence'), 'report_claims', 'notice_evidence', ['evidence_span_id'], ['id'])
    op.create_index(op.f('ix_report_claims_evidence_span_id'), 'report_claims', ['evidence_span_id'], unique=False)
    op.drop_index(op.f('ix_report_claim_citations_report_claim_id'), table_name='report_claim_citations')
    op.drop_index(op.f('ix_report_claim_citations_evidence_id'), table_name='report_claim_citations')
    op.drop_table('report_claim_citations')
    # ### end Alembic commands ###
